name: CI

on: [push, pull_request]

jobs:
  composer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 7.3, 7.4, 8.0, 8.1, 8.2, 8.3 ]

    steps:
      - uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}

      - name: Composer
        uses: php-actions/composer@run-as-current-user
        with:
          php_version: ${{ matrix.php }}

      - name: Archive build
        run: mkdir /tmp/github-actions/ && tar -cvf /tmp/github-actions/build.tar ./

      - name: Upload build archive for test runners
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-${{ runner.os }}-${{ matrix.php }}
          path: /tmp/github-actions

  phpunit:
    runs-on: ubuntu-latest
    needs: [composer]
    strategy:
      matrix:
        php: [ 7.3, 7.4, 8.0, 8.1, 8.2, 8.3 ]

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-artifact-${{ runner.os }}-${{ matrix.php }}
          path: /tmp/github-actions

      - name: Extract build archive
        run: tar -xvf /tmp/github-actions/build.tar ./

      - name: PHP Unit tests
        uses: php-actions/phpunit@v3
        with:
          version: 9
          php_version: ${{ matrix.php }}
          php_extensions: xdebug
          configuration: test/phpunit/phpunit.xml
          bootstrap: vendor/autoload.php

  phpstan:
    runs-on: ubuntu-latest
    needs: [composer]
    strategy:
      matrix:
        php: [ 7.3, 7.4, 8.0, 8.1, 8.2, 8.3 ]

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-artifact-${{ runner.os }}-${{ matrix.php }}
          path: /tmp/github-actions

      - name: Extract build archive
        run: tar -xvf /tmp/github-actions/build.tar ./

      - name: PHP Static Analysis
        uses: php-actions/phpstan@v3
        with:
          path: src/
          php_version: ${{ matrix.php }}
